import type { TExercise } from '../types/exercise';
import type { TExerciseName } from '../types/exerciseName';

export const exercises: TExercise<TExerciseName>[] = [
  {
    name: "ALTERNATE_TOE_TAPS",
    positions: ['FLOOR'],
    muscles: ['ADDUCTORS', 'HIP_FLEXORS'],
    bodyParts: ["LOWER_LEG", 'UPPER_LEG', 'ABDOMINAL'],
    bodySections: ['LEGS', 'HIPS', 'CORE'],
    variations: ['LOW_IMPACT', ],
    demos: ['https://darebee.com/exercises/toe-tap-hops.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "ANKLE_DORSIFLEXIONS",
    positions: ['SEATED', 'STANDING', 'SUPINE'],
    muscles: ['SHINS'],
    bodyParts: ['ANKLES', 'FEET'],
    bodySections: ['FEET'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "ANKLE_EVERSIONS",
    positions: ['SEATED', 'STANDING', 'SUPINE'],
    muscles: ['LOWER_LEG'],
    bodyParts: ['ANKLES', 'FEET', 'LOWER_LEG'],
    bodySections: ['FEET', 'LEGS'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "ANKLE_INVERSIONS",
    positions: ['SEATED', 'STANDING', 'SUPINE'],
    muscles: ['LOWER_LEG'],
    bodyParts: ['ANKLES', 'FEET', 'LOWER_LEG'],
    bodySections: ['FEET', 'LEGS'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "ANKLE_ROLLS",
    positions: ['SEATED', 'SUPINE', 'STANDING'],
    muscles: ['LOWER_LEG'],
    bodyParts: ['ANKLES', 'FEET'],
    bodySections: ['FEET', 'LEGS'],
    variations: ['SINGLE_LEGGED'],
    demos: [''],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "ARCH_LIFTS",
    positions: ['SEATED', 'STANDING', 'SUPINE'],
    muscles: ['LOWER_LEG'],
    bodyParts: ['FEET', 'LOWER_LEG'],
    bodySections: ['FEET', 'LEGS'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "ARM_EXTENSIONS",
    positions: ['SEATED', 'STANDING', 'SUPINE'],
    muscles: ['TRICEPS'],
    bodyParts: ['ARMS'],
    bodySections: ['ARMS'],
    variations: [],
    demos: [''],
    categories: ['CALISTHENICS'],
  },
  {
    name: "ATG_SPLIT_SQUATS",
    positions: ['STANDING'],
    muscles: ['QUADS', 'HAMSTRINGS', 'ADDUCTORS', 'ABDUCTORS', 'CALVES'],
    bodyParts: ['LOWER_LEG', 'UPPER_LEG'],
    bodySections: ['LEGS'],
    variations: [],
    demos: ['https://barbend.com/atg-split-squat/'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "ATG_SQUATS",
    positions: ['STANDING'],
    muscles: ['QUADS', 'HAMSTRINGS', 'ADDUCTORS', 'ABDUCTORS', 'CALVES'],
    bodyParts: ['LOWER_LEG', 'UPPER_LEG'],
    bodySections: ['LEGS'],
    variations: [],
    demos: ['https://fitnessvolt.com/atg-squat/'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "BACK_EXTENSIONS",
    positions: ['PRONE'],
    muscles: ['ERECTOR_SPINAE', 'GLUTES'],
    bodyParts: ['LOWER_BACK', 'UPPER_BACK'],
    bodySections: ['BACK'],
    variations: [],
    demos: ['https://www.youtube.com/watch?v=Bw9YuQTTc58'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "BEAR_CRAWLS",
    positions: ['PRONE', 'FLOOR'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['INCLINED', 'DECLINED', 'ON_STAIRS'],
    demos: ['https://darebee.com/exercises/bear-crawl.html'],
    categories: ['CALISTHENICS', 'PRIMAL_MOVEMENTS', 'MOBILITY'],
  },
  {
    name: "BIRD_DOG_POSES",
    positions: ['PRONE', 'FLOOR'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['ON_KNEES', 'BENT_KNEES'],
    demos: ['https://darebee.com/exercises/arm-leg-raises.html'],
    categories: ['STABILITY', 'YOGA'],
  },
  {
    name: "BRIDGES",
    positions: ['SUPINE', 'FLOOR'],
    muscles: ['CORE', 'ERECTOR_SPINAE', 'GLUTES', 'HAMSTRINGS'],
    bodyParts: ['ABDOMINAL', 'LOWER_BACK', 'UPPER_LEG'],
    bodySections: ['BACK', 'CORE', 'LEGS'],
    variations: [],
    demos: ['https://darebee.com/exercises/bridges-exercise.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "BURPEES",
    positions: ['STANDING', 'SUPINE'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: [],
    demos: ['https://darebee.com/exercises/burpees-exercise.html'],
    categories: ['CALISTHENICS', 'MOBILITY'],
  },
  {
    name: "BUTT_KICKS",
    positions: ['STANDING'],
    muscles: ['HAMSTRINGS', 'GLUTES', 'CALVES' ],
    bodyParts: ['LOWER_LEG', 'UPPER_LEG', 'HIPS'],
    bodySections: ['LEGS'],
    variations: ['LOW_IMPACT'],
    demos: ['https://darebee.com/exercises/butt-kicks.html'],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "CALF_RAISES",
    positions: ['STANDING', 'SEATED'],
    muscles: ['CALVES'],
    bodyParts: ['LOWER_LEG'],
    bodySections: ['LEGS'],
    variations: ['SEATED', 'ON_STAIRS', 'ELEVATED'],
    demos: ['https://darebee.com/exercises/calf-raises.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "CAT_COW_POSES",
    positions: ['STANDING', 'SEATED', 'FLOOR', 'PRONE'],
    muscles: ['CORE', 'ERECTOR_SPINAE'],
    bodyParts: ['LOWER_BACK', 'UPPER_BACK'],
    bodySections: ['BACK', 'CORE'],
    variations: ['STANDING', 'SEATED'],
    demos: ['https://www.youtube.com/watch?v=ESJ6Ghvgr6k'],
    categories: ['YOGA'],
  },
  {
    name: "CRUNCHES",
    positions: ['FLOOR', 'SUPINE'],
    muscles: ['CORE', 'RECTUS_ABDOMINUS'],
    bodyParts: ['ABDOMINAL', 'CORE', 'TORSO'],
    bodySections: ['CORE'],
    variations: ['INCLINED', 'REVERSE'],
    demos: ['https://darebee.com/exercises/crunches-exercise.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "DIPS",
    positions: [],
    muscles: ['TRICEPS', 'DELTS'],
    bodyParts: ['ARMS', 'SHOULDERS'],
    bodySections: ['ARMS', 'SHOULDERS'],
    variations: [],
    demos: ['https://www.wikihow.com/Do-Dips'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "DOWNWARD_DOG_POSES",
    positions: ['PRONE', 'FLOOR'],
    muscles: ['CALVES', 'SHOULDER_GIRDLE', 'CORE'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['ON_KNEES'],
    demos: ['https://www.youtube.com/watch?v=ayQoxw8sRTk'],
    categories: ['YOGA'],
  },
  {
    name: "FLUTTER_KICKS",
    positions: ['SUPINE'],
    muscles: ['CORE'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: [],
    demos: ['https://darebee.com/exercises/flutter-kicks.html'],
    categories: ['CALISTHENICS', 'STABILITY'],
  },
  {
    name: "FORWARD_ARM_CIRCLES",
    positions: ['STANDING', 'KNEELING'],
    muscles: ['SHOULDER_GIRDLE'],
    bodyParts: ['SHOULDERS'],
    bodySections: ['SHOULDERS'],
    variations: ['REVERSE'],
    demos: ['https://darebee.com/exercises/raised-arms-circles.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "HIGH_KNEES",
    positions: ['STANDING'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['LOW_IMPACT'],
    demos: ['https://darebee.com/exercises/high-knees.html'],
    categories: ['MOBILITY'],
  },
  {
    name: "JUMPING_JACKS",
    positions: ['STANDING', 'SEATED'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['LOW_IMPACT', 'SEATED'],
    demos: ['https://darebee.com/exercises/jumping-jacks.html'],
    categories: ['CALISTHENICS', 'MOBILITY'],
  },
  {
    name: "KNEE_RAISES",
    positions: ['STANDING', 'SEATED'],
    muscles: ['HIP_FLEXORS', 'CORE'],
    bodyParts: ['UPPER_LEG', 'CORE'],
    bodySections: ['CORE', 'LEGS'],
    variations: ['ON_ALL_FOURS'],
    demos: [],
    categories: ['MOBILITY', 'STABILITY'],
  },
  {
    name: "LATERAL_LEG_RAISES",
    positions: ['STANDING', 'SIDE'],
    muscles: ['ABDUCTORS', 'CORE'],
    bodyParts: ['CORE', 'UPPER_LEG'],
    bodySections: ['CORE', 'LEGS'],
    variations: [],
    demos: ['https://darebee.com/exercises/side-leg-raises.html'],
    categories: ['CALISTHENICS', 'STABILITY'],
  },
  {
    name: "LEG_RAISES",
    positions: ['SUPINE'],
    muscles: ['CORE'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: ['BENT_KNEES'],
    demos: ['https://darebee.com/exercises/leg-raises.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "LUNGES",
    positions: ['STANDING'],
    muscles: ['ABDUCTORS', 'ADDUCTORS', 'QUADS', 'HAMSTRINGS', 'CALVES', 'CORE'],
    bodyParts: ['ANKLES', 'FEET', 'LOWER_LEG', 'UPPER_LEG', 'HIPS'],
    bodySections: ['LEGS', 'HIPS'],
    variations: ['REVERSE'],
    demos: ['https://darebee.com/exercises/forward-lunges.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "MOUNTAIN_CLIMBERS",
    positions: ['PRONE'],
    muscles: ['WHOLE_BODY'],
    bodyParts: ['WHOLE_BODY'],
    bodySections: ['WHOLE_BODY'],
    variations: ['LOW_IMPACT'],
    demos: ['https://darebee.com/exercises/climbers-exercise.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "NECK_ROLLS",
    positions: ['STANDING', 'SEATED', 'KNEELING'],
    muscles: ['NECK'],
    bodyParts: ['NECK'],
    bodySections: ['NECK'],
    variations: [],
    demos: [],
    categories: ['YOGA'],
  },
  {
    name: "PLANKS",
    positions: ['PRONE', 'FLOOR'],
    muscles: ['CORE'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: ['ON_KNEES'],
    demos: ['You know this one'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "PULL_UPS",
    positions: [],
    muscles: ['BICEPS', 'SHOULDER_GIRDLE', 'FOREARM', 'LATS', 'CORE'],
    bodyParts: ['ARMS', 'UPPER_BACK', 'CORE'],
    bodySections: ['ARMS', 'BACK', 'CORE'],
    variations: ['WIDE_GRIP', 'CLOSE_GRIP'],
    demos: ['Coming soon'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "PUSH_UPS",
    positions: ['FLOOR', 'PRONE'],
    muscles: ['CORE', 'SHOULDER_GIRDLE', 'PECS', 'DELTS'],
    bodyParts: ['ARMS', 'CORE', 'SHOULDERS'],
    bodySections: ['CORE', 'SHOULDERS', 'ARMS'],
    variations: ['ON_KNEES','WALL', 'INCLINED', 'DECLINED'],
    demos: ['https://darebee.com/exercises/push-ups.html'],
    categories: ['CALISTHENICS', 'STABILITY'],
  },
  {
    name: "REVERSE_ARM_CIRCLES",
    positions: ['STANDING', 'KNEELING'],
    muscles: ['SHOULDER_GIRDLE'],
    bodyParts: ['SHOULDERS'],
    bodySections: ['SHOULDERS'],
    variations: [],
    demos: ['https://darebee.com/exercises/raised-arms-circles.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "REVERSE_FLY",
    positions: ['STANDING', 'KNEELING'],
    muscles: ['LATS', 'TRAPS', 'ERECTOR_SPINAE', 'SHOULDER_GIRDLE'],
    bodyParts: ['UPPER_BACK', 'SHOULDERS'],
    bodySections: ['BACK', 'SHOULDERS'],
    variations: [],
    demos: ['https://darebee.com/exercises/chest-expansions.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "SCISSOR_KICKS",
    positions: ['FLOOR', 'SUPINE'],
    muscles: ['CORE', 'ABDUCTORS', 'ADDUCTORS'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: [],
    demos: ['https://darebee.com/exercises/scissors-exercise.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "SEATED_CALF_RAISES",
    positions: ['SEATED'],
    muscles: ['CALVES'],
    bodyParts: ['LOWER_LEG'],
    bodySections: ['LEGS'],
    variations: [],
    demos: [],
    categories: ['CALISTHENICS'],
  },
  {
    name: "SHOULDER_TAPS",
    positions: ['STANDING'],
    muscles: ['DELTS', 'TRICEPS'],
    bodyParts: ['SHOULDERS', 'ARMS'],
    bodySections: ['SHOULDERS', 'ARMS'],
    variations: ['ON_KNEES'],
    demos: ['https://darebee.com/exercises/standing-shoulder-taps.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "SIDE_PLANKS",
    positions: ['FLOOR', 'SIDE'],
    muscles: ['CORE', 'EXTERNAL_OBLIQUES', 'INTERNAL_OBLIQUES'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: [],
    demos: ['https://darebee.com/exercises/side-planks.html'],
    categories: ['CALISTHENICS', 'STABILITY'],
  },
  {
    name: "SPEED_SKATERS",
    positions: ['STANDING'],
    muscles: ['GLUTES', 'QUADS', 'HAMSTRINGS', 'CALVES', 'CORE'],
    bodyParts: ['CORE', 'UPPER_LEG', 'LOWER_LEG'],
    bodySections: ['CORE', 'LEGS'],
    variations: [],
    demos: ['https://darebee.com/exercises/side-to-side-jumps.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "SQUATS",
    positions: ['STANDING'],
    muscles: ['HAMSTRINGS', 'QUADS'],
    bodyParts: ['UPPER_LEG'],
    bodySections: ['LEGS'],
    variations: ['SINGLE_LEGGED'],
    demos: ['https://darebee.com/exercises/squats-exercise.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "SUPERHUMANS",
    positions: ['PRONE'],
    muscles: ['ERECTOR_SPINAE', 'GLUTES', 'DELTS'],
    bodyParts: ['LOWER_BACK', 'UPPER_BACK', 'SHOULDERS'],
    bodySections: ['BACK'],
    variations: [],
    demos: ['https://darebee.com/exercises/superman-stretch.html'],
    categories: ['CALISTHENICS'],
  },
  {
    name: "TOE_CURLS",
    positions: ['STANDING', 'SEATED', 'SUPINE', 'FLOOR'],
    muscles: ['FLEXORS'],
    bodyParts: ['FEET', 'TOES'],
    bodySections: ['FEET'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY'],
  },
  {
    name: "TOE_RAISES",
    positions: ['STANDING', 'SEATED', 'SUPINE', 'FLOOR'],
    muscles: ['EXTENSORS'],
    bodyParts: ['FEET', 'TOES'],
    bodySections: ['FEET'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY'],
  },
  {
    name: "TOE_SPLAYS",
    positions: ['STANDING', 'SEATED', 'SUPINE', 'FLOOR'],
    muscles: [],
    bodyParts: ['FEET', 'TOES'],
    bodySections: ['FEET'],
    variations: [],
    demos: [''],
    categories: ['MOBILITY'],
  },
  {
    name: "TOE_TOUCHES",
    positions: ['STANDING', 'SEATED', 'FLOOR', 'SUPINE'],
    muscles: ['HAMSTRINGS', 'GLUTES'],
    bodyParts: ['UPPER_LEG'],
    bodySections: ['LEGS'],
    variations: [],
    demos: [''],
    categories: [],
  },
  {
    name: "UPWARD_DOG_POSES",
    positions: ['FLOOR', 'PRONE'],
    muscles: ['TRICEPS', 'ERECTOR_SPINAE', 'GLUTES'],
    bodyParts: ['ARMS', 'UPPER_BACK', 'LOWER_BACK'],
    bodySections: ['ARMS', 'BACK', 'HIPS'],
    variations: [],
    demos: ['https://www.youtube.com/watch?v=cIX73v498u4'],
    categories: ['YOGA'],
  },
  {
    name: "TRUNK_TWISTS",
    positions: ['FLOOR', 'SUPINE'],
    muscles: ['CORE', 'EXTERNAL_OBLIQUES', 'INTERNAL_OBLIQUES'],
    bodyParts: ['CORE'],
    bodySections: ['CORE'],
    variations: ['STANDING'],
    demos: ['https://darebee.com/exercises/sitting-twists.html'],
    categories: [],
  },
  {
    name: "WALKOUT_PLANKS",
    positions: ['PRONE'],
    muscles: ['SHOULDER_GIRDLE', 'CORE'],
    bodyParts: ['SHOULDERS', 'CORE'],
    bodySections: ['ARMS', 'CORE'],
    variations: [],
    demos: ['https://darebee.com/exercises/plank-walkouts.html'],
    categories: ['CALISTHENICS', 'MOBILITY', 'STABILITY'],
  },
  {
    name: "WRIST_ROLLS",
    positions: ['STANDING', 'SEATED', 'KNEELING'],
    muscles: ['FOREARM', 'EXTENSORS', 'FLEXORS'],
    bodyParts: ['FOREARMS'],
    bodySections: ['ARMS'],
    variations: [],
    demos: [''],
    categories: ['CALISTHENICS'],
  },

];
