export enum EBodyParts {
	ARMS = 'Arms',
	ANKLES = 'Ankles',
	ELBOWS = 'Elbows',
	FINGERS = 'Fingers',
	HANDS = 'Hands',
	FEET = 'Feet',
	TOES = 'Toes',
	CORE = 'Core',
	FOREARMS = 'Forearm',
	UPPER_ARMS = 'Upper Arm',
	SHOULDERS = 'Shoulders',
	LOWER_BACK = 'Lower Back',
	UPPER_BACK = 'Upper Back',
	TORSO = 'Torso',
	NECK = 'Neck',
	ABDOMINAL = 'Abdominal',
	LOWER_LEG = 'Lower Leg',
	UPPER_LEG = 'Upper Leg',
	HIPS = 'Hips',
	WRISTS = 'Wrists',
	WHOLE_BODY = 'Whole Body'
}
