export enum EExerciseVariations {
	ALTERNATING='Alternating',
	CLOSE_GRIP='Close Grip',
	ON_ALL_FOURS='On All Fours',
	CROSSED_ARMS='Crossed Arms',
	CROSSED_LEGS='Crossed Legs',
	ELEVATED='Elevated',
	STANDING='Standing',
	DIAMOND='Diamond',
	HAND_STAND='Hand Stand',
	BENCH='Bench',
	REVERSE='Reverse',
	INCLINED='Inclined',
	DECLINED='Declined',
	BENT_KNEES='Bent Knees',
	ON_STAIRS='On Stairs',
	INVERTED='Inverted',
	LOW_IMPACT='Low Impact',
	ON_KNEES='On Knees',
	PIKE='PIKE',
	SEATED='Seated',
	SINGLE_LEGGED='Single Legged',
	SLOW='Slow',
	UPSIDE_DOWN='Upside Down',
	WALL='Wall',
	WIDE_GRIP='Wide Grip',
};
