export enum EMuscles {
	ABDUCTORS='Abductors',
	ADDUCTORS='Adductors',
	BICEPS='Biceps',
	CALVES='Calves',
	DELTS='DELTS',
	EXTENSORS='Extensors',
	EXTERNAL_OBLIQUES='External Obliques',
	FLEXORS='Flexors',
	FOREARM='Forearm',
	GLUTES='Glutes',
	HAMSTRING='Hamstring',
	HIP_FLEXORS='Hip Flexors',
	INTERNAL_OBLIQUES='Internal Obliques',
	LATS='Lats',
	PECS='Pecs',
	QUADS='Quads',
	RECTUS_ABDOMINUS='Rectus Abdominus',
	ROTATOR_CUFF='Rotator Cuff',
	SHINS='Shins',
	TRAPS='Traps',
	TRICEPS='Triceps',
};
