export const installed = 'Installed!';
export const notInstalled = 'NOT installed!';
export const thanks = 'Thank you!';
export const launchFromHomeScreen = 'Launch the app from your home screen for the best experience';
export const newUpdate = 'New update available!';
export const reloadToUpdate = 'Reload to update?'
export const getTheUpdate = 'GET THE UPDATE';
export const instantAccess = 'Instant access to your workouts!';
export const useOffline = 'Use SUIT YOURSELF offline!';
export const getTheApp = 'GET THE APP';
